🔧 CHORE 12) husky pre-commit 커밋 전 현재 브랜치가 develop 또는 main 일 경우 하지 못하도록 막음

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,17 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run lint
+
+BRANCH=`git rev-parse --abbrev-ref HEAD`
+PROTECTED_BRANCHES="^(master|develop)"
+
+echo "current branch: $BRANCH"
+echo "protected branches: $PROTECTED_BRANCHES"
+
+if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+then
+  echo -e "main 또는 develop에 commit할 수 없습니다."
+  echo -e "\n🚫 Cannot commit to local $BRANCH branch" && exit 1
+fi
+
+exit 0
